image: golang:1.14

stages:
  - build
  - test
  - dependency

build:
  tags:
    - um_ci
  stage: build
  before_script:
    - apt update -y
    - apt install -y libefivar-dev libefiboot-dev libblkid-dev
  script:
    - go build

test:
  tags:
    - um_ci
  stage: test
  before_script:
    - apt update -y
    - apt install -y libefivar-dev libefiboot-dev libblkid-dev
  script:
    - apt update -y
    - apt install -y parted dosfstools
    - go test $(go list ./... | grep -v "/vendor\|ssh*\|efi") -v -coverprofile .testCoverage.txt
    - go tool cover -func=.testCoverage.txt

whitesource:
  only:
    refs:
     - master
  tags:
    - whitesource_ci
  stage: dependency
  script:
    - java -jar /usr/bin/wss-unified-agent.jar -apiKey $WSS_API_KEY -projectToken $WSS_IAM_TOKEN -userKey $WSS_USER_KEY  -c ./ci/wss-um.conf -d ./ -scanComment $CI_COMMIT_SHORT_SHA