image: golang:1.14

before_script:
  - apt update -y
  - apt install -y libefivar-dev libefiboot-dev libblkid-dev

stages:
  - build
  - test
  - cyclonedx

build:
  tags:
    - um_ci
  stage: build
  script:
    - go build

test:
  tags:
    - um_ci
  stage: test
  script:
    - apt update -y
    - apt install -y parted dosfstools
    - go test $(go list ./... | grep -v "/vendor\|ssh*\|efi") -v -coverprofile .testCoverage.txt
    - go tool cover -func=.testCoverage.txt

dependency:
  only:
    refs: 
     - master
  tags:
    - cyclonedx_ci
  stage: cyclonedx
  script:
    - sed -i '/aos_common/d' ./go.mod
    - cyclonedx-go -o /tmp/um_bom.xml
    - curl -X 'POST' 'https://aos-dependency.westeurope.cloudapp.azure.com/api/v1/bom' -H "X-Api-Key:$DEP_API_KEY" -F 'projectName=aos-updatemanager' -F 'autoCreate=true' -F 'bom=@/tmp/um_bom.xml'
