image: golang:1.14

stages:
  - build
  - test

build:
  tags:
    - um_ci
  stage: build
  script:
    - go build

test:
  tags:
    - um_ci
  stage: test
  script:
    - apt update
    - apt install libssl-dev -y
    - cp ./data/crt.pem  /etc/ssl/certs/
    - echo "-------   Run Unit tests   -------"
    - go test $(go list ./... | grep -v "/vendor\|ssh*") -v -coverprofile .testCoverage.txt
    - go tool cover -func=.testCoverage.txt

