[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.4.1"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "2.0.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"

[[constraint]]
  branch = "master"
  name = "github.com/tmc/scp"

[[constraint]]  
  name = "gitpct.epam.com/nunc-ota/aos_common"
  source = "https://gitlab+deploy-token-2:xKzx4NezaMzp6x9uUdJ4@gitpct.epam.com/nunc-ota/aos_common.git"
  revision = "88c6d63b08ce053e1786cb012d00a7a8e47f9dab"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
